CODE_PATH="/home/ajain/Desktop/SRE_Automations/sre-ansible"
PATH="/home/ajain/Desktop/SRE_Automations/sre-ansible"
DOMAIN_JOIN="ubuntu20-action.yml"
NAGIOS_DEP="nag_dep.yml"
NAGIOS_CLIENT="nagios_client.yml"
SPLUNK="splunk_forwarder.yml"
LOG_PATH="/home/ajain/Desktop/SRE_Automations"